#!/usr/bin/env bash
# Cloud Agent environment bootstrap for the arcgis-ingest-connectors pipeline.
#
# Idempotent: safe to re-run. Prepares durable state that persists into an
# environment snapshot:
#   - system packages (Python 3.13, PostgreSQL 16 + PostGIS, OCR tooling)
#   - a Python 3.13 virtualenv at .venv with the connector deps + pytest
#   - a local "ingestion" database owned by "ingest_app", migrated to head
#   - a gitignored .env pointing DATABASE_URL at the local Postgres
#
# Per-boot work (starting the Postgres server) lives in .cursor/start.sh.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PG_VERSION=16
PG_USER=ingest_app
PG_PASSWORD=change-me
PG_DB=ingestion

echo "[install] installing system packages"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common

# Python 3.13 (project requires >=3.13; not in the Ubuntu 24.04 default repos).
if ! command -v python3.13 >/dev/null 2>&1; then
  sudo add-apt-repository -y ppa:deadsnakes/ppa
  sudo apt-get update -y
fi

sudo apt-get install -y --no-install-recommends \
  python3.13 python3.13-venv python3.13-dev \
  "postgresql-${PG_VERSION}" \
  "postgresql-${PG_VERSION}-postgis-3" \
  "postgresql-${PG_VERSION}-postgis-3-scripts" \
  libpq5 libpq-dev \
  tesseract-ocr poppler-utils \
  curl git

echo "[install] ensuring PostgreSQL cluster is running"
if ! pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
  sudo pg_ctlcluster "${PG_VERSION}" main start || sudo service postgresql start || true
fi
# Wait for the socket to accept connections before issuing DDL.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "[install] provisioning role '${PG_USER}' and database '${PG_DB}'"
# SUPERUSER is required so migration 001 can CREATE EXTENSION postgis. This is a
# throwaway local dev database, never production.
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PG_USER}') THEN
    CREATE ROLE ${PG_USER} LOGIN PASSWORD '${PG_PASSWORD}';
  END IF;
END \$\$;
ALTER ROLE ${PG_USER} SUPERUSER;
SQL
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = '${PG_DB}'" \
  | grep -q 1 || sudo -u postgres createdb -O "${PG_USER}" "${PG_DB}"

echo "[install] writing .env (gitignored)"
if [ ! -f .env ]; then
  cat > .env <<ENV
# Local development .env (gitignored). Generated by .cursor/install.sh.
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=${PG_DB}
DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@localhost:5432/${PG_DB}
# Skip GCS raw-landing uploads in local dev / CI (connectors degrade gracefully).
DISABLE_GCS=1
ENV
fi

echo "[install] creating Python 3.13 virtualenv and installing dependencies"
if [ ! -x .venv/bin/python ]; then
  python3.13 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
python -m pip install --upgrade pip setuptools wheel
pip install -r connectors/requirements.txt
# pytest is not in the runtime requirements; the suite needs it.
pip install pytest

echo "[install] applying database migrations"
export PYTHONPATH="${REPO_DIR}/connectors"
python db/run_migrations.py

echo "[install] done"
